p1/urls.py
from django.contrib import admin
from django.urls import path, include

#LOGIN DJANGO, DELETE IN CASE OF ERR
from django.views.generic.base import TemplateView
from django.conf.urls import url

urlpatterns = [
    path('', include('pi.urls')),	#pi es la APLICACION
    path('admin/', admin.site.urls),
    path('login/', include('django.contrib.auth.urls')),
    #DJANGO LOGIN, DEL IN CASE OF ERR

]

pi/urls.py
from django.urls import path
from . import views

#django login, del in case of err
from django.conf.urls import url
from django.http import HttpResponseRedirect
from django.views.generic.base import TemplateView
from django.urls import include, reverse


app_name = 'pi'

urlpatterns=[
    path('', views.IndexView.as_view()),
    path('index/', views.IndexView.as_view(), name = 'index'),
    path('<int:pk>/',views.HomeView.as_view(), name='home'),
    path('accounts/', include('django.contrib.auth.urls'), name='login'),
    path('consultar/', views.ConsultarPedido.as_view(), name='consultar'),
    path('consultar/<int:id>',views.ConsultarPedido.as_view(), name='detailPedido'),
]

pizza/pi/urls.py
from django.urls import path, include, reverse
from django.conf.urls import url
from django.http import HttpResponseRedirect
from django.views.generic.base import TemplateView
from . import views


app_name='pi'

urlpatterns = [
    path('', views.indexView.as_view()),
    path('index/', views.indexView.as_view(), name='index'),

    path('<int:pk>', views.pizzasView.as_view(), name='pizzas'),
    path('accounts/', include('django.contrib.auth.urls'), name='login'),





]

pizza/pizza/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('django.contrib.auth.urls')),
    path('', include('pi.urls')),

]

pi/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db.models import manager

#para trabajar con fechas
import datetime
from django.utils import timezone

# Create your models here.

class Ingrediente(models.Model):
    ingrediente_id = models.IntegerField(primary_key=True)
    nom_ingrediente = models.CharField(max_length=25)

    def __str__(self):
        return self.nom_ingrediente

class Pizza(models.Model):

	pizza_id = models.IntegerField(primary_key=True)
	nom_pizza = models.CharField(max_length=30)
	precio = models.FloatField()
	objects = models.Manager()

	def __str__(self):
		return self.nom_pizza

class TipoMasa(models.Model):

	tipo_masa_id = models.IntegerField(primary_key=True)
	nom_tipo = models.CharField(max_length=7)

	def __str__(self):
		return self.nom_tipo

class Hecha_De(models.Model):
	corr_hec_de=models.AutoField(primary_key=True)
	pizza=models.ForeignKey(Pizza,on_delete=models.CASCADE)
	ingrediente=models.ForeignKey(Ingrediente,on_delete=models.CASCADE)
	tipomasa=models.ForeignKey(TipoMasa,on_delete=models.CASCADE)

	def __str__(self):
		pass
		
#nuevos
class Empleado(models.Model):
	cod_empleado=models.IntegerField(primary_key=True)
	nom_empleado=models.CharField(max_length=40)
	password_empleado=models.CharField(max_length=16,blank=False)

	def __str__(self):
		return self.nom_empleado

	@receiver(post_save, sender = User)
	def crear_usuario_perfil(sender, instance, created, **kwargs):
		if created:
			Empleado.objects.create(empleado=instance)

	@receiver(post_save, sender=User)
	def guardar_usuario_perfil(sender, instance, **kwargs):
		instance.perfil.save()


class Cliente(models.Model):
	cod_cliente=models.AutoField(primary_key=True)
	"""
	el autofield es para poner un nombre personalizado
	a una id generada automaticamente
	y no usar la que provee django por defecto (id)
	"""
	nom_cliente=models.CharField(max_length=40)
	dir_cliente=models.CharField(max_length=100)
	tel_cliente=models.BigIntegerField()


class Pedido(models.Model):
	cod_pedido=models.IntegerField(primary_key=True)
	fec_pedido=models.DateTimeField()
	objects = models.Manager()

	def __str__(self):
		return self.cod_pedido

class Detalle_Pedido(models.Model):
	corr_det_ped=models.AutoField(primary_key=True)
	pizza=models.ForeignKey(Pizza,on_delete=models.CASCADE)
	pedido=models.ForeignKey(Pedido,on_delete=models.CASCADE)		
	cant_pedido=models.IntegerField()
#nuevos
class Registro(models.Model):
	cod_registro=models.AutoField(primary_key=True)
	cod_empleado=models.ForeignKey(Empleado, on_delete=models.CASCADE)
	cod_pedido=models.ForeignKey(Pedido, on_delete=models.CASCADE)
	cod_cliente=models.ForeignKey(Cliente, on_delete=models.CASCADE)

pizza/pi/models.py
from django.db import models

# Create your models here

class Ingrediente(models.Model):
    ingrediente_id = models.IntegerField(primary_key=True)
    nom_ingrediente = models.CharField(max_length=25)

    def __str__(self):
        return self.nom_ingrediente


class Pizza(models.Model):
    pizza_id = models.IntegerField(primary_key=True)
    nom_pizza = models.CharField(max_length=30)

    objects = models.Manager()

    def __str__(self):
        return self.nom_pizza

class TipoMasas(models.Model):
    tipo_Masa_Id = models.IntegerField(primary_key=True)
    nom_tipo = models.CharField(max_length=7)

    def __str__(self):
        return self.nom_tipo

class Hecha_De(models.Model):
    corr_hec_de = models.AutoField(primary_key=True)
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    ingrediente = models.ForeignKey(Ingrediente, on_delete=models.CASCADE)
    tipomasa = models.ForeignKey(TipoMasas, on_delete=models.CASCADE)

    def __str__(self):
        return
        pass

class Empleado(models.Model):
    cod_empleado = models.IntegerField(primary_key=True)
    nom_empleado = models.CharField(max_length=40)
    pass_empleado = models.CharField(max_length=20, blank=False)

    objects = models.Manager()

    def __str__(self):
        return self.nom_empleado

class Cliente(models.Model):
    cod_cliente = models.IntegerField(primary_key=True)
    nom_cliente = models.CharField(max_length=40)
    dir_cliente = models.CharField(max_length=100)
    tel_cliente = models.BigIntegerField()

class Pedido(models.Model):
    cod_pedido = models.IntegerField(primary_key=True)
    fec_pedido = models.DateTimeField()

class Detalle_Pedido(models.Model):
    corr_det_ped = models.AutoField(primary_key=True)
    pizza = models.ForeignKey(Pizza,on_delete=models.CASCADE)
    cant_pedido = models.IntegerField()


class Registro(models.Model):
    cod_registro = models.AutoField(primary_key=True)
    cod_empleado = models.ForeignKey(Empleado,on_delete=models.CASCADE)
    cod_pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    cod_cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)

pi/views.py
from django.shortcuts import render
from .models import *
from django.views import generic
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
# Create your views here.

class IndexView(generic.ListView):
	template_name='index.html'
	context_object_name='pizza_list'

	def get_queryset(self):
		return Pizza.objects.all()

class HomeView(generic.DetailView):
	model=Pizza
	template_name='home.html'

#comentar en caso de err

class LoginView(generic.DetailView):
	model=Empleado
	template_name='registration/login.html'

#...

class ConsultarPedido(generic.ListView):
	model = Pedido
	template_name = 'pages/ConsultarPedido.html'
	context_object_name = 'detalle'



def detallePedido(request, cod_pedido):
	pedido = get_object_or_404(Pedido, pk=cod_pedido)
	return render(request, 'pages/Pedido_detalle.html', {'pedido': pedido})
#nuevo
def home(request, pizza_id):
	pizza=get_object_or_404(Pizza, pk=pizza_id)
	#return HttpResponse("estas mirando la pizza: %s." % pizza_id)
	return render(request,'home.html', {'pizza':pizza})


#comentar en caso de error
"""
def login(request, string):
	return render(request,'pi/login.html')
#......
"""

pizza/pi/views.py
from django.views import generic
from django.urls import reverse
from .models import Pizza, Empleado
from django.shortcuts import render, get_object_or_404
from django.views.generic.base import TemplateView
from django.http import HttpResponseRedirect


class indexView(generic.ListView):

    template_name = 'index.html'
    context_object_name = 'pizza_list'

    def get_queryset(self):
        return Pizza.objects.all()

    def logout_request(request):
        logout(request)
        messages.info(request, "Logged out successfully!")
        return redirect("main:homepage")

    def login(self):
        template_name='login.html'
        return HttpResponseRedirect(reverse('login'))

class pizzasView(generic.DetailView):
    model = Pizza
    template_name = 'pizzas.html'

def pizzas(request, pizza_id):
    pizza = get_object_or_404(Pizza, pk=pizza_id)
    return render(request, 'pizzas.html', {'pizza': pizza})

pi/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}Base we{% endblock %}</title>
</head>
<body>
	{% block content %}
	contenido we
	{% endblock %}
</body>
</html>

pi/templates/home.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">



<!DOCTYPE html>
<html>
<head>
	<title>Opciones</title>
</head>
<body>
	<div>
		<ol>
			<h1>{{ pizza.nom_pizza }}</h1>
			<p>Acá podria ir la descripción de la pizza</p>
		</ol>
		<div>
			<p>Acá la descripción completa</p>
		</div>
	</div>
</body>
</html>

pi/templates/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>
		{% block title %}Pizzeria{% endblock %}
	</title>
	<script src="js/jquery.js"></script>
	<script type="text/javascript">
		function openDialog(){
			$('#overlay').fadeIn('fast',function(){
				$('#popup').css('display','block');
				$('#popup').animate({'left':'30%'},500);
			});
		}
		function closeDialog(id){
			$('#'+id).css('position','absolute');
			$('#'+id).animate({'left':'-100%'},500,function(){
				$('#+id').css('position','fixed');
				$('#+id').css('left','100%');
				//creo que ese de ahi es un :
				$('#overlay').fadeOut('fast');
			});
		}
	</script>
</head>
<body>
	<div class="container">
		<div class="navbar navbar-dark bg-dark">
			<div class="container">
				<div class="navbar-header">HEADER OF NAVBAR *PRUEBAPOPUP
					<button class="submit">
						{% if user.is_authenticated %}
    					<a href="{% url 'pi:logout' %}">logout</a>
						{% else %}
  						<a href="{% url 'pi:login' %}">login</a>
						{% endif %}
					</button>
				</div>
			</div>
		</div>
	</div>

	<div id="popup" class="popup">
		<a onclick="closeDialog('popup');" class="close"></a>
		<div>
			{% if user.is_authenticated %}
			<button class="button" type="button">BOTON
				<a href="http://127.0.0.1/the-bug-genie/thebuggenie/pizzeriaprueba/issues/new">Reportar bug</a></button>
			{% else %}
			<button class="button" type="button">BOTON
				<a href="home">NOHOME</a></button>
			{% endif %}
		</div>
	</div>


	{% if pizza_list %}
	<ul>
		{% for pizza in pizza_list %}
		<li>
			<a href="{% url 'pi:home' pizza.pizza_id %}">{{ pizza.nom_pizza }}
			</a>
		</li>
		{% endfor %}
	</ul>
	{% else %}
		<p>No pizza disponible we:(</p>
	{% endif %}
	
	{% block content %}
		<ul>
			<li>
				<a href="{% url 'pi:consultar' %}">Consultar pedido</a>			</li>
		</ul>
	{% endblock %}

</body>
</html>