p1/urls.py
from django.contrib import admin
from django.urls import path, include

#LOGIN DJANGO, DELETE IN CASE OF ERR
from django.views.generic.base import TemplateView
from django.conf.urls import url

urlpatterns = [
    path('', include('pi.urls')),	#pi es la APLICACION
    path('admin/', admin.site.urls),
    path('login/', include('django.contrib.auth.urls')),
    #DJANGO LOGIN, DEL IN CASE OF ERR

]

pizza/pi/urls.py
from django.urls import path, include, reverse
from django.conf.urls import url
from django.http import HttpResponseRedirect
from django.views.generic.base import TemplateView
from . import views


app_name='pi'

urlpatterns = [
    path('', views.indexView.as_view()),
    path('index/', views.indexView.as_view(), name='index'),

    path('<int:pk>', views.pizzasView.as_view(), name='pizzas'),
    path('accounts/', include('django.contrib.auth.urls'), name='login'),





]

pizza/pizza/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('django.contrib.auth.urls')),
    path('', include('pi.urls')),

]

pizza/pi/models.py
from django.db import models

# Create your models here

class Ingrediente(models.Model):
    ingrediente_id = models.IntegerField(primary_key=True)
    nom_ingrediente = models.CharField(max_length=25)

    def __str__(self):
        return self.nom_ingrediente


class Pizza(models.Model):
    pizza_id = models.IntegerField(primary_key=True)
    nom_pizza = models.CharField(max_length=30)

    objects = models.Manager()

    def __str__(self):
        return self.nom_pizza

class TipoMasas(models.Model):
    tipo_Masa_Id = models.IntegerField(primary_key=True)
    nom_tipo = models.CharField(max_length=7)

    def __str__(self):
        return self.nom_tipo

class Hecha_De(models.Model):
    corr_hec_de = models.AutoField(primary_key=True)
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    ingrediente = models.ForeignKey(Ingrediente, on_delete=models.CASCADE)
    tipomasa = models.ForeignKey(TipoMasas, on_delete=models.CASCADE)

    def __str__(self):
        return
        pass

class Empleado(models.Model):
    cod_empleado = models.IntegerField(primary_key=True)
    nom_empleado = models.CharField(max_length=40)
    pass_empleado = models.CharField(max_length=20, blank=False)

    objects = models.Manager()

    def __str__(self):
        return self.nom_empleado

class Cliente(models.Model):
    cod_cliente = models.IntegerField(primary_key=True)
    nom_cliente = models.CharField(max_length=40)
    dir_cliente = models.CharField(max_length=100)
    tel_cliente = models.BigIntegerField()

class Pedido(models.Model):
    cod_pedido = models.IntegerField(primary_key=True)
    fec_pedido = models.DateTimeField()

class Detalle_Pedido(models.Model):
    corr_det_ped = models.AutoField(primary_key=True)
    pizza = models.ForeignKey(Pizza,on_delete=models.CASCADE)
    cant_pedido = models.IntegerField()


class Registro(models.Model):
    cod_registro = models.AutoField(primary_key=True)
    cod_empleado = models.ForeignKey(Empleado,on_delete=models.CASCADE)
    cod_pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    cod_cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)

pizza/pi/views.py
from django.views import generic
from django.urls import reverse
from .models import Pizza, Empleado
from django.shortcuts import render, get_object_or_404
from django.views.generic.base import TemplateView
from django.http import HttpResponseRedirect


class indexView(generic.ListView):

    template_name = 'index.html'
    context_object_name = 'pizza_list'

    def get_queryset(self):
        return Pizza.objects.all()

    def logout_request(request):
        logout(request)
        messages.info(request, "Logged out successfully!")
        return redirect("main:homepage")

    def login(self):
        template_name='login.html'
        return HttpResponseRedirect(reverse('login'))

class pizzasView(generic.DetailView):
    model = Pizza
    template_name = 'pizzas.html'

def pizzas(request, pizza_id):
    pizza = get_object_or_404(Pizza, pk=pizza_id)
    return render(request, 'pizzas.html', {'pizza': pizza})

pizza/templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

pizza/templates/home.html
<!-- templates/home.html -->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
    <p><a href="{% url 'logout' %}">logout</a> </p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">login</a>
{% endif %}
{% endblock %}

pizza/templates/index.html
{% load static %}


<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

<head>
<title>
		{% block title %}Pizzeria{% endblock %}
</title>
</head>
{% block body %}
<body>
	<div class="container">
		<div class="nav-bar">
			<div class="container">
				<div class="nav-bar-header">HEADER OF NAVBAR

						{% if user.is_authenticated %}
    					<a href="{% url 'pi:logout' %}">logout</a>
						{% else %}
  						<a href="{% url 'pi:login' %}">login</a>
						{% endif %}

				</div>
			</div>
		</div>
	</div>
	{% if pizza_list %}
	<ul>
		{% for pizza in pizza_list %}
		<li>
			<a href="{% url 'pi:pizzas' pizza.pizza_id %}">{{ pizza.nom_pizza }}	{{ pizza.pizza_id}}		</a>
		</li>
		{% endfor %}
	</ul>
	{% else %}
		<p>No pizza disponible we:(</p>
	{% endif %}
	
	{% block content %}
		<h2>
			Contenido
		</h2>
	{% endblock %}
{% endblock %}
</body>

pizza/templates/login2.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <title>LOGIN</title>
</head>
<body>
  <form>
    <div class="form-group">
      <label for="exampleInputEmail1">Email address</label>
      <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
      <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">Password</label>
      <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
    </div>
    <div class="form-check">
      <input type="checkbox" class="form-check-input" id="exampleCheck1">
      <label class="form-check-label" for="exampleCheck1">Check me out</label>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</body>
</html>

pizza/templates/password_reset_form.html
{% extends "base_generic.html" %}
{% block content %}

<form action="" method="post">{% csrf_token %}
    {% if form.email.errors %} {{ form.email.errors }} {% endif %}
        <p>{{ form.email }}</p>
    <input type="submit" class="btn btn-default btn-lg" value="Reset password" />
</form>

{% endblock %}

pizza/templates/pizzas.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'home.css' %}">



<!DOCTYPE html>
<html>
<head>
	<title>Opciones</title>
</head>
<body>
	<div>
		<ol>
			<h1>{{ pizza.nom_pizza }}</h1>
			<p>Acá podria ir la descripción de la pizza</p>
		</ol>
		<div>
			<p>Acá la descripción completa</p>
		</div>
	</div>
</body>
</html>